### ISSUE TITLE
Readme links to inaccessible design doc on Gitlab

### ISSUE THREAD

**Issue by holly-hacker** [timmyjose/maze_rs#1]
The README links to a design doc on https://gitlab.com/timmyjose/maze_project/blob/master/doc/Design.md, which is inaccessible to the public.

**Comment by timmyjose** [comment]
@HoLLy-HaCKeR Hey, thanks for pointing that out! I must have messed that up while migrating from my (now defunct) Gitlab account. I'll get it fixed now.

**Comment by timmyjose** [comment]
Fixed in latest `master`.
